### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sobolevn**
Closes https://github.com/dry-python/returns/issues/547

### CODE REVIEW

**Comment by sobolevn** [comment]
@thepabloaguilar awesome! It works!
Снимок экрана 2020-09-21 в 18 24 04

**Comment by sobolevn** [comment]
I will close this PR after the build will be finised.

**Comment by thepabloaguilar** [comment]
Greaat!! 🎉 🎉 🎉 🎉

**Comment by sobolevn** [comment]
AWESOME! https://returns--621.org.readthedocs.build/en/621/

**Comment by thepabloaguilar** [comment]
This preview is so handy to view the changes before the merge!

**Pull request closed without merging**
