### PR TITLE
Issue 1642

### LINKED ISSUE #1642: Breaking deserialization backward compatibility between 0.19.0 and 0.20.0
# Bug report

In version 0.20.0 changes to `returns/primitives/container.py` were presented for `__setstate__` and `__getstate__` functions of `BaseContainer` to fix None serialization. Unfortunately, these changes break deserialization backward compatibility, so any object serialized with returns<=0.19.0 cannot be deserialized at all with returns==0.20.0.

## What's wrong

If an object of type `Result` was serialized with `returns==0.19.0`, then during deserialization the next error would be seen:

```
File /data/anaconda3/lib/python3.9/site-packages/returns/primitives/container.py:62, in BaseContainer.__setstate__(self, state)
     59 def __setstate__(self, state: _PickleState) -> None:
     60     """Loading state from pickled data."""
     61     object.__setattr__(  # noqa: WPS609
---> 62         self, '_inner_value', state['container_value'],
     63     )

TypeError: byte indices must be integers or slices, not str
```

That happens, because the `state` object is not a dict with the 'container_value'  key (how it should be if serialized with 0.20.0), but a byte-like (serialized) object.

## How is that could be

Though backward compatibility is not always a goal, here at least partial (deserialization) backward compatibility could be achieved.

The simple way is to add a check to the `__setstate__` function, such as whether the `state` object is an instance of `dict` and the 'container_value' key is presented. Probably the only downside of this would be the slightly slower deserialization of containers.

## System information

- `python` version: 3.10
- `returns` version: 0.19.0 and 0.20.0

### PR DESCRIPTION
**Pull request by maybe-hello-world**
# I have made things!

## Checklist

- [x] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [x] I have created at least one test case for the changes I have made
- [ ] I have updated the documentation for the changes I have made
- [x] I have added my changes to the `CHANGELOG.md`

## Related issues

Closes #1642

### CODE REVIEW

**Review by sobolevn — APPROVED** [review]
Thank you!

**Comment by maybe-hello-world** [comment]
Should I do anything else for this PR do be merged?

**Comment by sobolevn** [comment]
Please, fix the failing ci :)

**Comment by maybe-hello-world** [comment]
Oh, thought that the test was unrelated.
Done.

**Review by sobolevn — APPROVED** [review]
Thanks again!

**Comment by sobolevn** [comment]
@thepabloaguilar are you up to make a new patch version release? :)

**Comment by thepabloaguilar** [comment]
> @thepabloaguilar are you up to make a new patch version release? :)

Released!

**Pull request merged**
