### PR TITLE
Add `Maybe.{is_some, is_nothing}`

### PR DESCRIPTION
**Pull request by homeworkprod**
As suggested and discussed in #278.

Contains docstring-based tests. Is this sufficient?

### CODE REVIEW

**Comment by homeworkprod** [comment]
Alright, checks are finally green!

> The only question I have: what about `Result`?
> Can we create an uniform interface for it too?

I have opened #301 for that; please take a look.

**Comment by homeworkprod** [comment]
@sobolevn, how can we continue from here?

And is #301 what you had in mind, or something more "uniform" as in the same method names in both `Maybe` and `Result`?

**Comment by homeworkprod** [comment]
@sobolevn, is there anything I can do to move this forward? Are you unsure about something?

I'd like to have something like this before continuing to integrate the library into my project.
And the upcoming long Easter weekend is a good time for me to work on that :)

**Comment by sobolevn** [comment]
@homeworkprod yes, I am a bit unsure about new methods in our classes. The thing is I don't really like methods. I like functions. 

And we already have one to solve this problem. And this PR introduces logic duplication in exchange of better Developer Experience. That's always hard to reason about 🙂

**Comment by homeworkprod** [comment]
Isn't the whole point of this library a better developer experience?

**Comment by thedrow** [comment]
In this case, I'd prefer to have a single flag and not two.

Will `can_unwrap` fit?

**Comment by homeworkprod** [comment]
> In this case, I'd prefer to have a single flag and not two.

I do see the convenience of that.

However, as I've laid out in [my comment](https://github.com/dry-python/returns/issues/278#issuecomment-602203163), separate methods/functions is what "Maybe" implementations in popular programming languages' standard libraries provide.

There are quite a few things *returns* does in its own ways, but I think it's worth to consider what people wanting to (or having to) use it can expect given their prior experiences.

**Comment by homeworkprod** [comment]
@sobolevn, I'm surprised that you're hesitating with this suggestion as you have marked my comment with a heart (which then made me go on and submit this PR). I guess you just changed your mind afterwards?

**Comment by sobolevn** [comment]
@homeworkprod you idea is awesome. We are just thinking about the best naming / design for this exact feature. There are different options:

1. `is_successful` as it is know, because fewer methods is better
2. Unified getters for all types: `Result`, `Maybe`, `IOResult`, `TaskResult`, etc
3. Different methods for different containers as suggested here and in #301 
4. `__bool__` cast

There's also no need to hurry. New release is still in heavy development and we will ship this feature in it.

I really appreciate you involvement in this project! Thanks a lot for raising issues, discussing ideas, and sendings PRs! 👍

**Comment by homeworkprod** [comment]
Thanks for clarifying!

**Comment by sobolevn** [comment]
Thanks a lot for the PR! I am going to close it, since we plan to support another API.

See https://github.com/dry-python/returns/issues/95#issuecomment-629625442

There's also an additional way to do the same thing: `isinstance(value, Maybe.success_type)`

**Pull request closed without merging**
