### PR TITLE
Bumps sphinx from 3.5.4 to 4.0.2 in /docs & Fix build docs

### PR DESCRIPTION
**Pull request by thepabloaguilar**
I've bumped the `sphinx` in our docs requirements to version `4.0.2` AND to make `sphinxcontrib-mermaid` I've added an temporary fix!

And also I need to lock the `Jinja` version, it was the root of the problem on read the docs!

### CODE REVIEW

**Comment by thepabloaguilar** [comment]
https://github.com/typlog/sphinx-typlog-theme/issues/22

Tks @chrizzFTD for highlight the differences on jinja versions!

**Comment by thepabloaguilar** [comment]
@sobolevn Now we can merge all the dependabot's PRs after a rebase!

**Review by sobolevn — APPROVED** [review]
Thanks a lot! It really was a pain to deal with!

**Comment by sobolevn** [comment]
Btw, `classes` project has this problem too.

**Pull request merged**
