### PR TITLE
Bump mypy to 1.6.1

### PR DESCRIPTION
**Pull request by sobolevn**
Closes https://github.com/dry-python/returns/pull/1709

### CODE REVIEW

**Comment by andersk** [comment]
Bisecting mypy shows that both failures were first triggered by python/mypy@14418bc3d2c38b9ea776da6029e9d9dc6650b7ea:

- python/mypy#15837

**Comment by sobolevn** [comment]
Yeap, I have to rework how `detach_callable` works now.

**Comment by sobolevn** [comment]
Sure, please, go ahead :)

**Comment by thepabloaguilar** [comment]
I've tried but I have no idea 😄 

Why do you think `detach_callable` is the problem?

**Pull request closed without merging**
