### PR TITLE
make assert_trace work with `@safe` (#862)

### PR DESCRIPTION
**Pull request by ftruzzi**
# I have made things!

## Checklist

- [x] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [x] I have created at least one test case for the changes I have made
- [ ] I have updated the documentation for the changes I have made
- [x] I have added my changes to the `CHANGELOG.md`

## Related issues

🙏 Please, if you or your company finds `dry-python` valuable, help us sustain the project by sponsoring it transparently on https://github.com/sponsors/dry-python. As a thank you, your profile/company logo will be added to our main README which receives hundreds of unique visitors per day.

### CODE REVIEW

**Review by sobolevn — APPROVED** [review]
Thanks a lot!

**Review by thepabloaguilar — COMMENTED** [review]
Sorry for the delay!!

This PR resolves the problem, but I think we're putting some dirty things from our pytest plugin inside the `core`.
Do you mind any other solution?

**Comment by ftruzzi** [comment]
@thepabloaguilar thanks making me think a bit more about it!

How about moving `_DesiredFunctionFound` back to the plugin and making it a subclass of `BaseException` instead? Should not be caught by `@safe` this way and it's definitely a cleaner fix.

**Comment by sobolevn** [comment]
I am not the codeowner for this feature, but I like it! 👍

**Comment by thepabloaguilar** [comment]
@ftruzzi I have another idea that I'll be glad if you could test it before!!
Let's move our `pytest.fail(...)` from [here](https://github.com/dry-python/returns/blob/master/returns/contrib/pytest/plugin.py#L70) to [here](https://github.com/dry-python/returns/blob/master/returns/contrib/pytest/plugin.py#L138)!

Our trace function will be something like this:
```python
def _trace_function(
    trace_type: _ReturnsResultType,
    function_to_search: _FunctionType,
    frame: FrameType,
    event: str,
    arg: Any,
) -> None:
    is_desired_type_call = (
        event == 'call' and frame.f_code is trace_type.__code__
    )
    if is_desired_type_call:
        current_call_stack = inspect.stack()
        function_to_search_code = getattr(function_to_search, '__code__', None)
        for frame_info in current_call_stack:
            if function_to_search_code is frame_info.frame.f_code:
                pytest.fail(...)
                return
```

**Comment by ftruzzi** [comment]
Sorry @thepabloaguilar I think I'm a bit confused -- shouldn't the test **pass** if the `function_to_search_code is frame_info.frame.f_code` condition is satisfied?

**Comment by thepabloaguilar** [comment]
@ftruzzi you're totally right, my bad, it should be:

```python
def _trace_function(
    trace_type: _ReturnsResultType,
    function_to_search: _FunctionType,
    frame: FrameType,
    event: str,
    arg: Any,
) -> None:
    is_desired_type_call = (
        event == 'call' and frame.f_code is trace_type.__code__
    )
    if is_desired_type_call:
        current_call_stack = inspect.stack()
        function_to_search_code = getattr(function_to_search, '__code__', None)
        for frame_info in current_call_stack:
            if function_to_search_code is frame_info.frame.f_code:
                return
        pytest.fail(...)
```

**Comment by thepabloaguilar** [comment]
Well, we can't do what I've suggested! I remembered why hahaha
We can't say from inside the `_trace_function` if we did not find the desired function 'cause we are not on top of all the posible calls since `_trace_function` is called every time that a call for any function is made!

Just let me illustrate my explanation:

```python
# CALL STACK
# Call 6
# Call 5
* Call 4 -> `_trace_function` is called, we can't say here if the desired function was not found since there will be more two calls
* Call 3
* Call 2
* Call 1
```

**Comment by thepabloaguilar** [comment]
Please @ftruzzi continue with your solution, if @sobolevn doesn't see any problem with modifying `@safe` to not handle our "internal" exceptions!

**Comment by sobolevn** [comment]
I like this solution https://github.com/dry-python/returns/pull/863#issuecomment-800944015

**Review by sobolevn — APPROVED** [review]
Thanks!

**Comment by ftruzzi** [comment]
Thank you both @sobolevn and @thepabloaguilar, it's nice to learn new stuff and contribute :)

**Pull request merged**
