### PR TITLE
Better exception inference for `@safe` and `@impure_safe`

### PR DESCRIPTION
**Pull request by sobolevn**
I got this idea when reviewing your PR :)

CC @RomanMIzulin 
Refs https://github.com/dry-python/returns/pull/1870

### CODE REVIEW

**Comment by RomanMIzulin** [comment]
Honestly, I do not get the idea of having ResultE when there is a Result[ValueType,ErrorType] with ErrorType with second arg. Just for typing a block of code when we are sure there is an error I guess. But if code is not deep just Result is okey?

**Comment by RomanMIzulin** [comment]
Is the goal of this MR to proxy specific Exception rather than just Exception?
@sobolevn

**Comment by sobolevn** [comment]
> Honestly, I do not get the idea of having ResultE when there is a Result[ValueType,ErrorType] with ErrorType with second arg

Back in the day we didn't have typevar defaults, so I had to add one more type alias for the common case. Right now we can deprecate `*E` aliases and use `TypeVar(..., default=Exception)` for `ResultLike`

**Comment by RomanMIzulin** [comment]
and update doc like here https://returns.readthedocs.io/en/latest/pages/result.html#aliases
@sobolevn maybe issue for that?

**Comment by sobolevn** [comment]
@RomanMIzulin yes, sure, go ahead!

**Pull request merged**
