### PR TITLE
Issue 1396 - Broken link to drylabs.io on the bottom of README

### LINKED ISSUE #1396: Broken link to drylabs.io on the bottom of README
The bottom of the README file links to drylabs.io, which seems to be an abandoned or lost domain ("parking").
Is there a new location, or has the mentioned organisation ceased to exist?

### PR DESCRIPTION
**Pull request by ryangrose**
Replace drylabs.io with dry-labs.github.io (working as of 2022-09-09)

# I have made things!

## Checklist

- [x] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [ ] I have created at least one test case for the changes I have made
- [ ] I have updated the documentation for the changes I have made
- [x] I have added my changes to the `CHANGELOG.md`

## Related issues

- Closes #1396

### CODE REVIEW

**Review by sobolevn — COMMENTED** [review]
Let's just remove it :)

**Comment by ryangrose** [comment]
I think the poetry install for read the docs should be `poetry install --dev`? Looks like the docs dependencies are in dev

[link to pyproject.toml](https://github.com/dry-python/returns/blob/master/pyproject.toml#L94)

**Comment by ryangrose** [comment]
> Let's just remove it :)

Ah just saw this! Makes sense :) I've changed the PR to remove it and rebased to remove the old commits

**Review by sobolevn — APPROVED** [review]

**Comment by sobolevn** [comment]
Thanks

**Pull request merged**
