### PR TITLE
Use bind instead of map in example

### PR DESCRIPTION
**Pull request by nurumaik**
Read the docs, and saw no need of updating and explaining bind right there, so I'm modifying only the code part

https://github.com/dry-python/returns/issues/488

### CODE REVIEW

**Comment by nurumaik** [comment]
Idk how to link issue though

**Comment by nurumaik** [comment]
So your library is doing smth weird indeed, just as I thought first

map on Optional[T] is working like bind on Maybe[T]. My brain expected that if we map None to Nothing and x to Some x, then map method should work like this:

```python
Some(1).map(lambda x: return x * 2) == Some(2)
Some(1).map(lambda x: return None) == Some(None)
Some(1).bind(lambda x: return None) == Nothing
```

Guess all that weirdness comes from python "type" system, sorry for the confusion :)

**Comment by sobolevn** [comment]
Yes, 
```bash
» python -c 'from returns.maybe import Some; print(Some(1).map(lambda _: None))'
<Nothing>
```

This is intentional. Because `Some(None)` is a really strange thing to have in Python. 
See #314

**Comment by sobolevn** [comment]
Hey, @nurumaik! 👋 

Thanks again for submitting this fix! And for raising the discussion.
I hope that it is now clear, what is going on in this example. I will 100% add a note about `Some(None)` to it and then close #488 

Feel free to ask any questions you have! 👍

**Comment by nurumaik** [comment]
> Hey, @nurumaik! 👋
> 
> Thanks again for submitting this fix! And for raising the discussion.
> I hope that it is now clear, what is going on in this example. I will 100% add a note about `Some(None)` to it and then close #488
> 
> Feel free to ask any questions you have! 👍

Sorry, it was too hard to change documentation back, so I changed the code to conform to my changes in docs instead

https://github.com/dry-python/returns/pull/510

**Pull request closed without merging**
